config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects do
    resources :runs
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/projects/:project_id/runs/:id/report(/:suite)', to: 'runs#report', format: :json, as: 'report', defaults: { suite: 'dashboard' }
  post '/projects/:id/refresh', to: 'projects#refresh', as: 'refresh'
  get '/projects/:id(/:branch)/targets', to: 'projects#targets', as: 'targets', defaults: { branch: 'master', format: :json}
  get '/projects/:id(/:branch)/environments', to: 'projects#environments', as: 'environments', defaults: { branch: 'master', format: :json}

  mount ActionCable.server => '/cable'

end

app/models/project.rb
class Project
  include Mongoid::Document
  embeds_many :runs
  embeds_many :settings
  field :name, type: String
  field :repo_url, type: String
  field :next_run_no, type: Integer, default: 1

  before_validation :strip_whitespace

  private
  def strip_whitespace
    self.repo_url = repo_url.strip unless repo_url.nil?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :environments,
                                     :destroy, :refresh, :targets]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @runs = @project.runs
    params[:project_id] = @project.id
  end


  def targets
    @targets = ['all'] << @project.settings.where(branch: params[:branch]).first[:targets].map {|t| t[0]}
    @targets.flatten!
    respond_to do |format|
      format.json { render :targets, status: :ok, location: @project }
    end
  end

  def environments
    env = @project.settings.where(branch: params[:branch]).first[:environments] || {}
    @environments = ['all'] << env.map {|t| t[0]}
    @environments.flatten!
    respond_to do |format|
      format.json { render :environments, status: :ok, location: @project }
    end
  end
  # POST /projects/refresh
  # POST /projects/refresh.json
  def refresh
    ProjectImporterJob.perform_later(params[:id])
    respond_to do |format|
      format.html { redirect_to @project, notice: 'Updating Project' }
      format.json { render :show, status: :ok, location: @project }
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    logger.info @project.to_yaml
    respond_to do |format|
      if @project.save
        logger.info @project.to_yaml
        id = @project.id.to_s
        ProjectImporterJob.perform_later(id)
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :repo_url)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def import_properties(project)
    settings = settings_from_git(project)
    broadcast_update(project, settings)
  end

  def broadcast_update(project, settings)
    data = ApplicationController.render partial: 'projects/settings', locals: {project: project, active_branch: 'master'}
    ActionCable.server.broadcast("settings_#{project.id}", body: data)
  end



  def next_run_no(project)
    run_id = project.next_run_no
    project.next_run_no = run_id + 1
    project.save
    run_id
  end

  private

  def get_branches(branches)
    branches.select{|b| b.remote }.reject {|b| b.name.include?('HEAD') }
  end

  def settings_from_git(project)
    FileUtils.rm_rf("/tmp/#{project.name}") if Dir.exists? "/tmp/#{project.name}"
    settings = []
    begin
      Dir.chdir('/tmp/') do
        g = Git.clone(project.repo_url, project.name)
        get_branches(g.branches).each do |branch|
          g.branch(branch.full).checkout
          data = YAML.load(File.open("#{project.name}/properties.yml")).symbolize_keys
          setting = Setting.new
          setting[:branch] = branch.name
          setting[:targets] = data[:targets] || {}
          setting[:environments] = data[:environments] || {}
          setting[:options] = data[:options] || {}
          setting[:shared_example_gems] = data[:shared_example_gems] || []
          setting[:environment] = data[:environment] || {}
          setting[:variables] = data[:variables] || {}
          settings << setting
        end
        project.settings = settings
        project.save
      end
    rescue StandardError => e
      logger.info e.message
      logger.info e.backtrace.join("\n")
      raise e
    ensure
      FileUtils.rm_rf("/tmp/#{project.name}") if Dir.exists? "/tmp/#{project.name}"
    end
    settings
  end
end

app/views/projects/_form.html.haml
= simple_form_for @project, html: {},  wrapper: :horizontal_form do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |message|
          %li= message
  .row
    .col
      = f.input :name, input_html: { class: "#{input_style} string required"}
    .col
  .row
    .col
      = f.input :repo_url, input_html: { class: "#{input_style} string required"}
    .col
  .form-group
    .actions
      = f.submit 'Save', class: button_style
      = link_to 'Cancel', projects_path, class: button_style

app/views/projects/_run_form.html.haml
= simple_form_for(:run, url: project_runs_path(project_id: @project.id),wrapper: :horizontal_form, method: :post) do |f|
  .form-row
    .col
      = f.input 'Task', input_html: { name: 'run[target]', id: 'run_target', value: 'all', class: "#{input_style} string required"}
      = f.input 'branch', as: :hidden, input_html: { name: 'run[branch]', id: 'run_branch', value: 'master'}
    .col
      = f.submit 'New Run', class: button_style
    .col

app/views/projects/_settings.html.haml
%b Settings
%select{id: 'branchSelect', name: 'branchSelect'}
  - project.settings.each do |branch|
    %option{value: "#{branch.branch}", selected: branch.branch == 'master'}
      = branch.branch
= fa_link_to 'sync', refresh_path(project), 'refresh', title: 'edit', method: :post, class: button_style
%div{class: 'tab-content'}
  - project.settings.each do |branch|
    %div{id: "#{branch.branch}", role: 'tabpane1', class: "tab-pane fade #{branch.branch == active_branch ? 'active show' : ''}"}

      %div.settings-section
      %span.yaml-key branch:
      %span.settings-body
        = branch.branch

      %div.settings-section
        %span.yaml-key options:
        %span
          %a{'data-toggle': 'collapse', 'aria-expanded': false, role: 'button',
          'aria-controls': "#{branch.branch}_options", href: "\##{branch.branch}_options",
          class: 'collapse-button'} +

        %div.settings-body{id: "#{branch.branch}_options", class: collapse_css(true)}
          = render_yaml branch.options, ['options'], 1

      %div.settings-section
        %span.yaml-key targets
        %span
          %a{'data-toggle': 'collapse', 'aria-expanded': false, role: 'button',
          'aria-controls': "#{branch.branch}_targets", href: "\##{branch.branch}_targets",
          class: 'collapse-button'} +

        %div.settings-body{id: "#{branch.branch}_targets", class: collapse_css(true)}
          = render_yaml branch.targets, ['targets'], 1

      %div.settings-section
        %span.yaml-key environments:
        %span
          %a{'data-toggle': 'collapse', 'aria-expanded': false, role: 'button',
          'aria-controls': "#{branch.branch}_environments", href: "\##{branch.branch}_environments",
          class: 'collapse-button'} +

        %div.settings-body{id: "#{branch.branch}_environments", class: collapse_css(true)}
          = render_yaml branch.environments, ['environments'], 1

      %div.settings-section
        %span.yaml-key variables:
        %span
          %a{'data-toggle': 'collapse', 'aria-expanded': false, role: 'button',
          'aria-controls': "#{branch.branch}_variables", href: "\##{branch.branch}_variables",
          class: 'collapse-button'} +

        %div.settings-body{id: "#{branch.branch}_variables", class: collapse_css(true)}
          = render_yaml branch.variables, ['variables'], 1

      %div.settings-section
        %span.yaml-key environment:
        %span
          %a{'data-toggle': 'collapse', 'aria-expanded': false, role: 'button',
          'aria-controls': "#{branch.branch}_environment", href: "\##{branch.branch}_environment",
          class: 'collapse-button'} +

        %div.settings-body{id: "#{branch.branch}_environment", class: collapse_css(true)}
          = render_yaml branch.environment, ['environment'], 1

      %div.settings-section
        %span.yaml-key shared_example_gems:
        %span
          %a{'data-toggle': 'collapse', 'aria-expanded': false, role: 'button',
          'aria-controls': "#{branch.branch}_shared_example_gems", href: "\##{branch.branch}_shared_example_gems",
          class: 'collapse-button'} +

        %div.settings-body{id: "#{branch.branch}_shared_example_gems", class: collapse_css(true)}
          = render_yaml branch.shared_example_gems, ['shared_example_gems'], 1

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table.table
  %thead
    %tr
      %th Name
      %th Repo url
      %th
      %th
      %th

  %tbody
    - @projects.each do |project|
      %tr
        %td= project.name
        %td= project.repo_url
        %td= link_to 'Show', project
        %td= link_to 'Edit', edit_project_path(project)
        %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%input{type: 'hidden', id: 'projectId', value: @project.id}
%input{type: 'hidden', id: 'pageType', value: 'project_show'}

%p#notice= notice

%p
  %div
    %div{class: 'project-title'}= @project.name
    = @project.repo_url

#settingsDiv
  = render partial: 'settings', locals: {project: @project, active_branch: nil}
%div
  = render 'run_form'
%div
  %br
%div
  = render template: 'runs/index'

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path