config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects do
    resources :runs
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/projects/:project_id/runs/:id/report(/:suite)', to: 'runs#report', format: :json, as: 'report', defaults: { suite: 'dashboard' }
  post '/projects/:id/refresh', to: 'projects#refresh', as: 'refresh'
  get '/projects/:id(/:branch)/targets', to: 'projects#targets', as: 'targets', defaults: { branch: 'master', format: :json}
  get '/projects/:id(/:branch)/environments', to: 'projects#environments', as: 'environments', defaults: { branch: 'master', format: :json}

  mount ActionCable.server => '/cable'

end

app/models/run.rb
class Run
  include Mongoid::Document
  embedded_in :project

  field :status, type: String, default: 'pending'
  field :result, type: String
  field :notes, type: String
  field :targets, type: String, default: 'all'
  field :test_report, type: Hash, default: {}
  field :last_update, type: DateTime
  field :run_no, type: Integer
  field :summary, type: Hash
  field :branch, type: String

end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  include RunsHelper
  before_action :set_run, only: [:show, :edit, :update, :destroy, :report]
  before_action :set_project, except: [:update, :show, :edit]

  # GET /runs
  # GET /runs.json
  def index
    @project = Project.find(params[:project_id])
    @runs = @project.runs
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
  end

  # GET /runs/new
  def new
    @run = Run.new(project: @project)
  end

  # GET /runs/1/edit
  def edit
  end


  # POST /runs
  # POST /runs.json
  def create
    @run = Run.new(run_params.merge(project: @project))

    respond_to do |format|
      if @run.save
        TestRunnerJob.perform_later(@run.id.to_s, @project.id.to_s)
        format.html { redirect_to @run.project, notice: 'Run was successfully scheduled.' }
        format.json { render :show, status: :created, location: @run }
      else
        format.html { render :new }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runs/1
  # PATCH/PUT /runs/1.json
  def update
    respond_to do |format|
      if @run.update(run_params)
        data = render partial: 'runs/run', locals: {run: @run}
        ActionCable.server.broadcast("runs_#{@run.project.id}", id: @run.id.to_s, body: data)
        format.html { redirect_to @run, notice: 'Run was successfully updated.' }
        format.json { render :show, status: :ok, location: @run }
      else
        format.html { render :edit }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run.destroy
    respond_to do |format|
      format.html { redirect_to @run.project, notice: 'Run was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /runs/1/report/server1.json
  # GET /runs/1/report/server1.json
  def report
    @suite = params[:suite]
    respond_to do |format|
      format.html { render :report }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_run
    @project = Project.find(params[:project_id])
    @run = @project.runs.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def run_params
    params.require(:run).permit(:status, :result, :notes, :targets, :branch, :test_report => {}, :summary => {})
  end


end

app/helpers/runs_helper.rb
module RunsHelper

  def schedule_run(run)
    update_status(run, 'scheduling')
    swarm = DockerSwarm.new
    service = create_service(run, swarm)
    until swarm.task_finished(service) do
      update_status(run, swarm.check_service_status(service))
      sleep(0.2)
    end
    update_status(run, swarm.check_service_status(service))
    swarm.delete_service(service.name)
  end

  private

  def create_service(run, swarm)
    swarm.create_service name: "serverspec_#{Time.now.to_i}",
                         image: 'manager1:5000/andrewwardrobe/infratester-runner:latest',
                         restart_policy: 'none',
                         networks: [{"Target": 'infratester_launcher'}],
                         environment: %W[
                                       RUN_ID=#{run.id}
                                       PROJECT_ID=#{run.project.id}
                                       WEB_HOST=infratester_web
                                       GIT_BRANCH=#{run.branch}
                                       GIT_REPO=#{run.project.repo_url}
                                   ],
                         configs: [report_runner(swarm)]
  end

  def report_runner(swarm, config_name = 'reporter')
    file_hash = { "Name": '/usr/bin/post_results', "UID": '0', "GID": '0', mode: 0755  }
    if config = swarm.config_exists?('reporter')
      { "ConfigID": config['ID'], "ConfigName": config_name, "File": file_hash }
    else
      file_name = File.expand_path('../../templates/post_result.rb.erb', __FILE__)
      template = ERB.new(File.read(file_name)).result(binding)

      report_config = swarm.create_config name: config_name,
                                          filename: '/usr/bin/post_results',
                                          data: Base64.encode64(template)
      report_config[:"File"] = file_hash
      report_config
    end

  end

  def broadcast_update(run)
    data = ApplicationController.render partial: 'runs/run', locals: {run: run}
    ActionCable.server.broadcast("runs_#{run.project.id}", id: run.id.to_s, body: data)
  end

  def update_status(run, status)
    run.last_update = DateTime.now unless run.status == status
    run.status = status
    run.save
    broadcast_update(run)
  end



  def render_report(name, data, level = 0)
    css_class = "#{indentation_css(level)}"
    text = "%a{ id: '#{name}'}\n"
    text += "%div{class: 'test-report'}\n"
    text += "#{indent(1)}%div{class: '#{css_class}'}\n#{indent(2)}#{name}\n"
    data['examples'].each {|k,v| text += render_example_group(k, v, level + 1)}
    text += "#{indent(1)}%div{class: '#{css_class}'}#{data['summary_line']}\n"
    logger.info text
    render_haml text
  end

  def render_example_group(name, data, level = 1)
    css_class = "#{indentation_css(level)}"
    text = "#{indent(level)}%div{class: '#{css_class}'}\n#{indent(level+1)}#{name}\n"
    data.each do |inner_name, inner_data|
      if inner_data.key?('description')
        text += render_example(inner_name, inner_data, level + 1)
      else
        text += render_example_group(inner_name, inner_data, level + 1)
      end
    end
    text
  end

  def render_example(name, data, level)
    css_class = "#{test_result_css(data['status'])} #{indentation_css(level)}"
    "#{indent(level)}%div{class: '#{css_class}'}\n#{indent(level+1)}#{test_result_icon(data['status'])} #{name}\n"
  end



  def suite_status(data)
    logger.info data.to_yaml
    data['summary']['failure_count'].to_i > 0 ? 'failed' : 'passed'
  end

  def render_dashlink(key, data)
    render_haml "%a{href: 'report/#{key}', class: 'btn #{button_css(suite_status(data))}' } #{key}"
  end

  def row_css(status, result)
    if status == 'complete'
      if result == 'passed'
        'run-passed'
      elsif result == 'pending'
        'run-pending'
      elsif result == 'failed'
        'run-failed'
      end
    elsif status == 'failed'
      'run-failed'
    elsif status == 'error'
      'run-error'
    else
      'run-scheduled'
    end
  end

  def result_icon_css(status, result)
    if status == 'complete'
      if result == 'passed'
        'test-passed'
      elsif result == 'pending'
        'test-pending'
      elsif result == 'failed'
        'test-failed'
      end
    elsif status == 'failed'
      'test-failed'
    elsif status == 'error'
      'test-error'
    else
      'test-scheduled'
    end
  end

  def result_icon(status, result)
    if status == 'complete'
      if result == 'passed'
        fa_icon 'check-circle', type: :solid
      elsif result == 'pending'
        fa_icon 'clock', type: :solid
      elsif result == 'failed'
        fa_icon 'times-circle', type: :solid
      end
    elsif status == 'failed'
      fa_icon 'times-circle', type: :solid
    elsif status == 'error'
      fa_icon 'exclamation-circle', type: :solid
    else
      fa_icon 'clock', type: :solid
    end
  end

  def run_summary(run)

  end
end

app/views/runs/_dashboard.html.haml
%a{href: 'report/all', class: 'btn btn-primary' } all
- @run.test_report.each do |key, data|
 = render_dashlink(key, data)

app/views/runs/_form.html.haml
= form_with(model: [@project, @run], local: true) do |form|
  - if @run.errors.any?
    #error_explanation
      %h2
        = pluralize(run.errors.count, "error")
        prohibited this run from being saved:
      %ul
        - run.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :targets
    = form.text_field :targets, id: :run_targets
  .actions
    = form.submit

app/views/runs/_run.html.haml
%td ##{run.run_no} (#{run.branch || 'master' })
%td= run.status
%td
  = fa_icon 'check', type: :solid, text: run.summary[:passed_count] if run.summary
  = fa_icon 'times', type: :solid, text: run.summary[:failure_count] if run.summary
  = fa_icon 'clock', type: :regular, text: run.summary[:pending_count] if run.summary
%td{class: result_icon_css(run.status, run.result)}= result_icon(run.status, run.result)
%td
  - if run.last_update
    #{time_ago_in_words run.last_update} ago
  - else
    waiting for completion

app/views/runs/edit.html.haml
%h1 Editing Run
= render 'form', run: @run
= link_to 'Show', @run
|
= link_to 'Back', runs_path

app/views/runs/index.html.haml
%table{class: 'table table-dark'}
  %thead
  %tbody
    - @runs.each do |run|
      %tr{'data-href': project_run_url(run.project, run), class: 'run-row', id: "run_#{run.id}" }
        = render partial: 'runs/run', locals: { run: run }

app/views/runs/new.html.haml
%h1 New Run
= render 'form', run: @run
= link_to 'Back', project_runs_path

app/views/runs/report.html.haml
%h2 Test Report
- if @suite == 'dashboard'
  = render 'dashboard'
-elsif @suite == 'all'
  - @run.test_report.keys.each do |key|
    %a{href: '#'+key}= key
  - @run.test_report.each do |suite, report|
    = render_report(suite, report)
- else
  = render_report(@suite,@run.test_report[@suite])

app/views/runs/show.html.haml
%h2 Test Report
%div
  Run ID: #{@run.id}
%div
  Status: #{@run.status}
%div
  Result: #{@run.result}
%div
  Targets: #{@run.targets}
%div
  Message:
  %br
  #{@run.notes}
%br
%div
%div
  Test Reports:
  %div
    - @run.test_report.keys.each do |key|
      %a{href: '#'+key}= key


    - @run.test_report.each do |suite, report|
      = render_report(suite, report)

= link_to 'Delete', [@run.project, @run], method: :delete, data: { confirm: 'Are you sure?' }
|
= link_to 'Back', project_path(id: @run.project.id)